2022-09-08 20:12:11 - INFO - Training/evaluation parameters: Namespace(adam_eps=1e-06, adam_lr=5e-05, base_url='../data/tnews_public/', bert_cache='../config/chinese-roberta-wwm-ext', bert_dim=768, bert_dir='hfl/chinese-roberta-wwm-ext', bert_max_length=512, bert_padding='max_length', best_score=0.5, ckpt_file='save/BD/v13/model_.bin', data_path='../data/Toursim3.csv', device='cuda', dropout=0.1, log_file='log/BD/v13.log', lstm_batch_first=True, lstm_bidirectional=True, lstm_dropout=0.0, lstm_hidden_size=256, lstm_input_size=768, lstm_num_layers=2, lstm_reflector_size=256, max_epochs=10, max_steps=50000, n_gpu=1, num_class=3, num_workers=6, prefetch=12, print_steps=10, savedmodel_path='save/BD/v13', seed=2021, smoothing=0.0, stopWords='../stopword/hit_stopwords.txt', train_batch_size=24, val_batch_size=24, val_ratio=0.2, warmup_steps=1000, weight_decay=0.001, word2Vec='../word2vec/sgns.weibo.bigram-char.bz2', word2Vec_dim=300)
Some weights of the model checkpoint at hfl/chinese-roberta-wwm-ext were not used when initializing BertModel: ['cls.predictions.transform.dense.bias', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.weight', 'cls.predictions.decoder.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
2022-09-08 20:14:42 - INFO - Epoch 0 step 232: loss 0.430, {'accuracy': 0.8192, 'f1': 0.806, 'precision': 0.8099, 'recall': 0.8192}
2022-09-08 20:17:00 - INFO - Epoch 1 step 464: loss 0.445, {'accuracy': 0.8156, 'f1': 0.8072, 'precision': 0.8063, 'recall': 0.8156}
2022-09-08 20:19:17 - INFO - Epoch 2 step 696: loss 0.522, {'accuracy': 0.7977, 'f1': 0.78, 'precision': 0.7859, 'recall': 0.7977}
Traceback (most recent call last):
  File "/home/lenovo/anaconda3/envs/tfNLP/lib/python3.8/multiprocessing/queues.py", line 245, in _feed
    send_bytes(obj)
Traceback (most recent call last):
  File "main.py", line 100, in <module>
  File "/home/lenovo/anaconda3/envs/tfNLP/lib/python3.8/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/lenovo/anaconda3/envs/tfNLP/lib/python3.8/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/home/lenovo/anaconda3/envs/tfNLP/lib/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
    main()
  File "main.py", line 97, in main
    train_and_validate(args)
  File "main.py", line 72, in train_and_validate
    loss, results = validate(model, val_dataloader)
  File "main.py", line 20, in validate
    predictions.extend(pred_label_id.cpu().numpy())
KeyboardInterrupt
